config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  resources :categories
  resources :clients
  resources :suppliers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products
end

app/models/client.rb
class Client < ApplicationRecord
    has_many :sales
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :categories
  belongs_to :suppliers
  has_many :warehouse_records
end

app/models/sale.rb
class Sale < ApplicationRecord
    belongs_to :client
end

app/models/supplier.rb
class Supplier < ApplicationRecord
    has_many :products
    has_many :warehouse_records
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/warehouse_record.rb
class WarehouseRecord < ApplicationRecord
  belongs_to :supplier
  belongs_to :product
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:edit, :update, :destroy]

  def index
    @categorias = Category.all
  end

  def new
    @categoria = Category.new
  end

  def edit
  end

  def create
    @categoria = Category.new(category_params)

    respond_to do |format|
      if @categoria.save
        format.json { head :no_content }
        format.js
      else
        format.json { render json: @categoria.errors.full_messages, status: :unprocessable_entity }
        format.js { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @categoria.update(category_params)
        format.json { head :no_content }
        format.js
      else
        format.json { render json: @categoria.errors.full_messages, status: :unprocessable_entity }
        format.js { render :edit }
      end
    end
  end

  def destroy
    @categoria.destroy
    respond_to do |format|
      format.json { head :no_content }
      format.js
    end
  end

  private 
    def set_category
      @categoria = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:nombre, :descripcion)
    end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
    before_action :set_client, only: [:edit, :update, :destroy]

    def index
        @clientes = Client.all
    end

    def new
        @cliente = Client.new
    end

    def create 
        @cliente = Client.new(client_params)

        respond_to do |format|
            if @cliente.save
              format.json { head :no_content }
              format.js
            else
              format.json { render json: @cliente.errors.full_messages, status: :unprocessable_entity }
              format.js { render :new }
            end
        end
    end

    def edit
    end

    def update
        respond_to do |format|
            if @cliente.update(client_params)
                format.json {head :no_content}
                format.js
            else
                format.json { render json: @cliente.error.full_messages, status: :unprocessable_entity }
                format.js { render :edit }
            end
        end
    end

    def destroy
        @cliente.destroy
        respond_to do |format|
          format.json { head :no_content }
          format.js
        end
    end

    private

    def set_client
        @cliente = Client.find(params[:id])
    end

    def client_params
        params.require(:client).permit(:nombre, :direccion, :telefono)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
    before_action :set_supplier, only: [:edit, :update, :destroy]

  def index
    @proveedores = Supplier.all
  end

  def new
    @proveedor = Supplier.new
  end

  def edit
  end

  def create
    @proveedor = Supplier.new(supplier_params)
    
    respond_to do |format|
      if @proveedor.save
        format.json { head :no_content }
        format.js
      else
        format.json { render json: @proveedor.errors.full_messages, status: :unprocessable_entity }
        format.js { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @proveedor.update(supplier_params)
        format.json { head :no_content }
        format.js
      else
        format.json { render json: @proveedor.errors.full_messages, status: :unprocessable_entity }
        format.js { render :edit }
      end
    end
  end

  def destroy
    @proveedor.destroy
    respond_to do |format|
      format.json { head :no_content }
      format.js
    end
  end

  def buscador
    @resultados = Supplier.buscador(params[:termino]).map do |proveedor|
      {
          id: proveedor.id,
          nombre_proveedor: proveedor.nombre
      }
    end

    respond_to do |format|
      format.json { render :json => @resultados }
    end
  end

  private

  def set_supplier
    @proveedor = Supplier.find(params[:id])
  end

  def supplier_params
    params.require(:supplier).permit(:nombre, :direccion, :telefono)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/categories/_form.html.erb
<%= form_for @categoria, remote: true do |f| %>
    <div class="form-group">
      <h4 class="control-label">Datos de la categoría:</h4>
    </div>

    <div class="item form-group<%= @categoria.errors[:nombre].any? ? ' has-error has-feedback' : '' %>">
      <%= f.label :nombre, "Nombre de Categoría: " %>
      <div class="input-group">
        <%= f.text_field :nombre, {:class=> "form-control", :placeholder=>"Introduzca el nombre de la categoría..."} %>        
        <%if @categoria.errors[:nombre].any? %>
          <p class="bg-danger"><%= @categoria.errors[:nombre].to_s[/\w([^"]*)/] %></p>
        <% end %>
      </div>
    </div>

    <div class="item form-group<%= @categoria.errors[:descripcion].any? ? ' has-error has-feedback' : '' %>">
      <%= f.label :descripcion, "Descripción de la categoría: " %>
      <div class="input-group">
        <%= f.text_area :descripcion, {class: "form-control", :placeholder=>"Introduzca la descripción de la categoría..."} %>
        <%if @categoria.errors[:descripcion].any? %>
          <p class="bg-danger"><%= @categoria.errors[:descripcion].to_s[/\w([^"]*)/] %></p>
        <% end %>
      </div>
    </div>

    <div class="actions col-md-9 col-sm-9 col-xs-12 col-md-offset-3">
      <%= f.submit @categoria.new_record? ? "Crear Categoría" : "Actualizar Categoría", :class => "btn btn-success"%>
    </div>  
<% end %>

app/views/categories/_modal_categorias.html.erb
<!-- Modal -->
<div class="modal fade" id="modalCategorias" tabindex="-1" role="dialog" aria-labelledby="modalCategoriasLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="modal-categorias-title">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body-categorias modal-body" id="modal-body-categorias">
         
      </div>
      <div class="modal-footer" id="modal-footer-categorias">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>

app/views/categories/create.js.erb
$('#modalCategorias').modal('toggle');
$('#tablaCategorias').append(
    '<tr id="categoria_<%= @categoria.id %>" ><td><%= @categoria.nombre %></td><td><%= @categoria.descripcion %></td><td><%= link_to 'editar', edit_category_path(@categoria), html_options = {class: "btn btn-info btn-xs", remote: true} %> <%= link_to "Borrar", @categoria, remote: true, method: :delete, data: { confirm: "¿Borrar categoria: #{@categoria.nombre}?"}, class: "btn btn-danger btn-xs" %></td></tr>'
);

app/views/categories/destroy.js.erb
$('#categoria_<%= @categoria.id %>').fadeOut();

app/views/categories/edit.js.erb
$('#modal-categorias-title').html("Editar categoria");

$('.modal-body-categorias').html('<%= j render("form") %>');
 
$('#modalCategorias').modal("show");

app/views/categories/index.html.erb
<h1 class="h3 mb-2 text-gray-800">Categorias de productos</h1>

<div>  
  <%= link_to new_category_path, {remote: true, class: "btn btn-info", id: "anadir-categoria-btn"}  do %>
    <span class="fas fa-plus-square" ></span>
  <% end %>
</div>
<br />

<div class="card shadow mb-4">
    <div class="card-body">
        <div class="table-responsive">
            <table id="tablaCategorias" class="table table-bordered" width="100%">
                <thead>
                    <th>Nombre Categoria</th>
                    <th>Descripción</th>
                    <th></th>
                </thead>
                <tbody>
                    <% @categorias.each do |cat| %>
                        <tr id="categoria_<%= cat.id %>" >
                            <td><%= cat.nombre %></td>
                            <td><%= cat.descripcion %></td>
                            <td>
                            <%= link_to "editar", edit_category_path(cat), html_options = {class: "btn btn-info btn-xs", remote: true} %>
                            <%= link_to 'Borrar', cat, remote: true, method: :delete, data: { confirm: "¿Borrar categoria: #{cat.nombre}?"}, class: "btn btn-danger btn-xs" %>
                        </td>
                    <% end %>
                </tbody>
            </table>
        </div>
    </div>
</div>

<%= render 'modal_categorias' %>

app/views/categories/new.js.erb
// Add the dialog title
$('#modal-categorias-title').html("Nueva categoria");
 
// Render the new form
$('.modal-body-categorias').html('<%= j render("form") %>');
 
// Show the dynamic dialog
$('#modalCategorias').modal("show");

app/views/categories/update.js.erb
$('#modalCategorias').modal('toggle');
$('#categoria_<%= @categoria.id %>').replaceWith(
    '<tr id="categoria_<%= @categoria.id %>" ><td><%= @categoria.nombre %></td><td><%= @categoria.descripcion %></td><td><%= link_to 'editar', edit_category_path(@categoria), html_options = {class: "btn btn-info btn-xs", remote: true} %> <%= link_to "Borrar", @categoria, remote: true, method: :delete, data: { confirm: "¿Borrar categoria: #{@categoria.nombre}?"}, class: "btn btn-danger btn-xs" %></td></tr>'
);

app/views/clients/_form.html.erb
<%= form_for @cliente, { remote: true, multiple: true }  do |f| %>

    <div class="form-group">
      <h4 class="control-label">Datos del cliente:</h4>
    </div>

    <div class="item form-group<%= @cliente.errors[:nombre].any? ? ' has-error has-feedback' : '' %>">
      <%= f.label :nombre, "Nombre del cliente: " %>
      <div class="input-group">
        <%= f.text_field :nombre, {:class=> "form-control", :placeholder=>"Introduzca el nombre del cliente..."} %>        
        <%if @cliente.errors[:nombre].any? %>
          <p class="bg-danger"><%= @cliente.errors[:nombre].to_s[/\w([^"]*)/] %></p>
        <% end %>
      </div>
    </div>

    <div class="item form-group<%= @cliente.errors[:direccion].any? ? ' has-error has-feedback' : '' %>">
      <%= f.label :direccion, "Dirección del cliente: " %>
      <div class="input-group">
        <%= f.text_area :direccion, {class: "form-control", :placeholder=>"Introduzca la dirección del cliente..."} %>
        <%if @cliente.errors[:direccion].any? %>
          <p class="bg-danger"><%= @cliente.errors[:direccion].to_s[/\w([^"]*)/] %></p>
        <% end %>
      </div>
    </div>

    <div class="item form-group<%= @cliente.errors[:telefono].any? ? ' has-error has-feedback' : '' %>">
      <%= f.label :telefono, "Telefono del cliente: " %>
      <div class="input-group">
        <%= f.text_field :telefono, {:class=> "form-control", :placeholder=>"Introduzca el teléfono del cliente.."} %>        
        <%if @cliente.errors[:telefono].any? %>
          <p class="bg-danger"><%= @cliente.errors[:telefono].to_s[/\w([^"]*)/] %></p>
        <% end %>
      </div>
    </div>

    <div class="actions col-md-9 col-sm-9 col-xs-12 col-md-offset-3">
      <%= f.submit @cliente.new_record? ? "Crear Cliente" : "Actualizar Cliente", :class => "btn btn-success"%>
    </div>  
  <% end %>

app/views/clients/_modal_clientes.html.erb
<!-- Modal -->
<div class="modal fade" id="modalClientes" tabindex="-1" role="dialog" aria-labelledby="modalClientesLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="modal-clientes-title"></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body-clientes modal-body" id="modal-body-clientes">

      </div>
      <div class="modal-footer" id="modal-footer-clientes">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>

app/views/clients/create.js.erb
$('#modalClientes').modal('toggle');
$('#tablaClientes').append(
    '<tr id="cliente_<%= @cliente.id %>" ><td><%= @cliente.nombre %></td><td><%= @cliente.direccion %></td><td><%= @cliente.telefono %></td><td><%= link_to 'editar', edit_client_path(@cliente), html_options = {class: "btn btn-info btn-xs", remote: true} %> <%= link_to "Borrar", @cliente, remote: true, method: :delete, data: { confirm: "¿Borrar cliente: #{@cliente.nombre}?"}, class: "btn btn-danger btn-xs" %></td></tr>'
);

app/views/clients/destroy.js.erb
$('#cliente_<%= @cliente.id %>').fadeOut();

app/views/clients/edit.js.erb
$('#modal-clientes-title').html("Editar cliente");
 
$('.modal-body-clientes').html('<%= j render("form") %>');

$('#modalClientes').modal("show");

app/views/clients/index.html.erb
<!-- Page Heading -->
<h1 class="h3 mb-2 text-gray-800">Clientes</h1>
<!-- DataTales Example -->
<div>  
  <%= link_to new_client_path, {remote: true, class: "btn btn-info", id: "anadir-cliente-btn"}  do %>
    <span class="fas fa-plus-square" style=""></span>
  <% end %>
</div>
<br />
<div class="card shadow mb-4">
<div class="card-body">
    <div class="table-responsive">
    <table class="table table-bordered" id="tablaClientes" width="100%" cellspacing="0">
        <thead>
        <tr>
            <th>Nombre</th>
            <th>Dirección</th>
            <th>Teléfono</th>
            <th>Acciones</th>
        </tr>
        </thead>
        <tbody>
            <% @clientes.each do |clie| %>
            <tr id="cliente_<%= clie.id %>" >
                <td><%= clie.nombre %></td>
                <td><%= clie.direccion %></td>
                <td><%= clie.telefono %></td>
                <td>
                <%= link_to "editar", edit_client_path(clie), html_options = {class: "btn btn-info btn-xs", remote: true} %>
                <%= link_to "Borrar", clie, remote: true, method: :delete, data: { confirm: "¿Borrar cliente: #{clie.nombre}?"}, class: "btn btn-danger btn-xs" %>
                </td>
            </tr>
            <% end %>
        </tbody>
    </table>
    </div>
  </div>
</div>
<%= render 'modal_clientes' %>

app/views/clients/new.js.erb
$('#modal-clientes-title').html("Nuevo cliente");
 
$('.modal-body-clientes').html('<%= j render("form") %>');
 
$('#modalClientes').modal("show");

app/views/clients/update.js.erb
$('#modalClientes').modal('toggle');
$('#cliente_<%= @cliente.id %>').replaceWith(
    '<tr id="cliente_<%= @cliente.id %>" ><td><%= @cliente.nombre %></td><td><%= @cliente.direccion %></td><td><%= @cliente.telefono %></td><td><%= link_to 'editar', edit_client_path(@cliente), html_options = {class: "btn btn-info btn-xs", remote: true} %> <%= link_to "Borrar", @cliente, remote: true, method: :delete, data: { confirm: "¿Borrar cliente: #{@cliente.nombre}?"}, class: "btn btn-danger btn-xs" %></td></tr>'
);

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/suppliers/_form.html.erb
<%= form_for @proveedor, remote: true do |f| %>

    <div class="form-group">
      <h4 class="control-label">Datos del proveedor:</h4>
    </div>

    <div class="item form-group<%= @proveedor.errors[:nombre].any? ? ' has-error has-feedback' : '' %>">
      <%= f.label :nombre, "Nombre del Proveedor: " %>
      <div class="input-group">
        <%= f.text_field :nombre, {:class=> "form-control", :placeholder=>"Introduzca el nombre del proveedor..."} %>        
        <%if @proveedor.errors[:nombre].any? %>
          <p class="bg-danger"><%= @proveedor.errors[:categoria].to_s[/\w([^"]*)/] %></p>
        <% end %>
      </div>
    </div>

    <div class="item form-group<%= @proveedor.errors[:direccion].any? ? ' has-error has-feedback' : '' %>">
      <%= f.label :direccion, "Dirección del proveedor: " %>
      <div class="input-group">
        <%= f.text_area :direccion, {class: "form-control", :placeholder=>"Dirección del proveedor..."} %>
        <%if @proveedor.errors[:direccion].any? %>
          <p class="bg-danger"><%= @proveedor.errors[:direccion].to_s[/\w([^"]*)/] %></p>
        <% end %>
      </div>
    </div>

    <div class="item form-group<%= @proveedor.errors[:telefono].any? ? ' has-error has-feedback' : '' %>">
      <%= f.label :telefono, "Teléfono del Proveedor: " %>
      <div class="input-group">
        <%= f.text_field :telefono, {:class=> "form-control", :placeholder=>"Introduzca el teléfono del proveedor..."} %>        
        <%if @proveedor.errors[:telefono].any? %>
          <p class="bg-danger"><%= @proveedor.errors[:telefono].to_s[/\w([^"]*)/] %></p>
        <% end %>
      </div>
    </div>

    <div class="actions col-md-9 col-sm-9 col-xs-12 col-md-offset-3">
      <%= f.submit @proveedor.new_record? ? "Crear Proveedor" : "Actualizar Proveedor", :class => "btn btn-success"%>
    </div>  
  <% end %>

app/views/suppliers/_modal_proveedores.html.erb
<!-- Modal -->
<div class="modal fade" id="modalProveedores" tabindex="-1" role="dialog" aria-labelledby="modalProveedoresLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="modal-proveedores-title"></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body-proveedores modal-body" id="modal-body-proveedores">

      </div>
      <div class="modal-footer" id="modal-footer-proveedores">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>

app/views/suppliers/create.js.erb
$('#modalProveedores').modal('toggle');
$('#tablaProveedores').append(
    '<tr id="proveedor_<%= @proveedor.id %>" ><td><%= @proveedor.nombre %></td><td><%= @proveedor.direccion %></td><td><%= @proveedor.telefono %></td><td><%= link_to 'editar', edit_supplier_path(@proveedor), html_options = {class: "btn btn-info btn-xs", remote: true} %> <%= link_to "Borrar", @proveedor, remote: true, method: :delete, data: { confirm: "¿Borrar categoria: #{@proveedor.nombre}?"}, class: "btn btn-danger btn-xs" %></td></tr>'
);

app/views/suppliers/destroy.js.erb
$('#proveedor_<%= @proveedor.id %>').fadeOut();

app/views/suppliers/edit.js.erb
$('#modal-proveedores-title').html("Editar proveedor");
 
$('.modal-body-proveedores').html('<%= j render("form") %>');
 
$('#modalProveedores').modal("show");

app/views/suppliers/index.html.erb
<!-- Page Heading -->
<h1 class="h3 mb-2 text-gray-800">Proveedores</h1>
<div>  
  <%= link_to new_supplier_path, {remote: true, class: "btn btn-info", id: "anadir-proveedor-btn"}  do %>
    <span class="fas fa-plus-square" style=""></span>
  <%end%>
</div>
<br />
<div class="card shadow mb-4">
<div class="card-body">
    <div class="table-responsive">
    <table class="table table-bordered" id="tablaProveedores" width="100%" cellspacing="0">
        <thead>
        <tr>
            <th>Nombre </th>
            <th>Dirección </th>
            <th>Teléfono</th>
        </tr>
        </thead>
        <tbody>
        <% @proveedores.each do |prov| %>
        <tr id="proveedor_<%= prov.id %>" >
            <td><%= prov.nombre %></td>
            <td><%= prov.direccion %></td>
            <td><%= prov.telefono %></td>
            <td>
            <%= link_to "editar", edit_supplier_path(prov), html_options = {class: "btn btn-info btn-xs", remote: true} %>
            <%= link_to 'Borrar', prov, remote: true, method: :delete, data: { confirm: "¿Borrar proveedor: #{prov.nombre}?"}, class: "btn btn-danger btn-xs" %>
            </td>
        </tr>
        <% end %>
        </tbody>
    </table>
    </div>
  </div>
</div>
<%= render 'modal_proveedores' %>

app/views/suppliers/new.js.erb
$('#modal-proveedores-title').html("Nuevo proveedor");
 
$('.modal-body-proveedores').html('<%= j render("form") %>');
 
$('#modalProveedores').modal("show");

app/views/suppliers/update.js.erb
$('#modalProveedores').modal('toggle');
$('#proveedor_<%= @proveedor.id %>').replaceWith(
    '<tr id="proveedor_<%= @proveedor.id %>" ><td><%= @proveedor.nombre %></td><td><%= @proveedor.direccion %></td><td><%= @proveedor.direccion %></td><td><%= link_to 'editar', edit_supplier_path(@proveedor), html_options = {class: "btn btn-info btn-xs", remote: true} %> <%= link_to "Borrar", @proveedor, remote: true, method: :delete, data: { confirm: "¿Borrar proveedor: #{@proveedor.nombre}?"}, class: "btn btn-danger btn-xs" %></td></tr>'
);